spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring_web?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ehdgusdl2
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  config:
    activate:
      on-profile: local
  http:
    converters:
      preferred-json-mapper: gson